### ISSUE TITLE
Attributes missing after upgrading HA to version 2022.4.7

### ISSUE THREAD

**Issue by JensMKofoed** [jm-73/Indego#157] opened 2022-04-28 07:29 UTC
Hi

I don't know why but after upgrading to the lates version I can't find any attributes to the indego entities. I still have attributes on other entities from other integrations but not at the indego. Don't know if it's related to this intergration or HA it self.

Any ideas to troubleshoot?
kind regards
Jens

**Comment by qbushome** [comment] 2022-04-29 19:18
Same issue here, no entities. Also on 2022.4.7
Error in the logs:
Request to https://api.indego.iot.bosch-si.com/api/v1/alms/223603018/state?longpoll=true&timeout=300&last=64513 gave a unhandled error: Server disconnected

@JensMKofoed
Do you see the same error ?

**Comment by parkkralle** [comment] 2022-05-02 16:03
Hi I got the same Issue. Also I cant't clear any Alert in HA. In the Indego App I can clear all Alerts. Any Ideas?

**Comment by mhosse** [comment] 2022-05-04 14:55
Hi, same attribute issue here. But no such errors as @qbushome.

I am not completely sure but imo the issue started already with the HA update to 2022.4.0.

**Comment by Siggy101** [comment] 2022-05-13 21:13
I have the same here.  
I used to have some nice graphs of battery temperature but all attributes are now gone.  
@jm-73 Any chance that you can take a look for us?

**Comment by mhosse** [comment] 2022-05-14 18:50
Hi,
I was able to fix the issue. 
Here is the PR for the change: https://github.com/jm-73/Indego/pull/159

**Comment by Siggy101** [comment] 2022-05-15 20:10
> Hi, I was able to fix the issue. Here is the PR for the change: #159

Thanks for the link, that does indeed look like it might be the root cause.
Forgive my lack of knowledge but do I need to do something or have you made a change that will be in a future release of the Indego integration (meaning I just have to wait and then update the integration once it's available)?

**Comment by mhosse** [comment] 2022-05-16 03:59
> do I need to do something or have you made a change that will be in a future release of the Indego integration (meaning I just have to wait and then update the integration once it's available)?

The plan is that @jm-73 will merge the PR and create a new release containing the fix. 
Nevertheless, you can apply the change to your HA manually. But this requires a bit knowledge about custom components and write access to the files.

**Comment by Siggy101** [comment] 2022-05-16 07:49
Thanks @mhosse.  All is clear now.
I just had a look at your PR and I think I can manage those 2 edits.  
Let me go see if I can break some stuff :)

**Comment by Siggy101** [comment] 2022-05-16 08:46
Hmm, so  I got busy with nano.
I only had one of the 2 references to device_state_attributes; line 106.  I did not have the 2nd one on line 110.
I edited line 106 to read extra_state_attributes, restarted everything, but the temps are still not being polled.  
I have gone back in and I confirm that the code edit has worked.  Any clues as to why that might be?

**Comment by jm-73** [comment] 2022-06-06 12:15
Fixed in 4.0

**Closed by jm-73** 2022-06-06 12:15 UTC
