### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by Ialocin7** [jm-73/Indego#51] opened 2020-05-28 21:59 UTC
I have a Bosch Indego s+ 400, but i can´t connect to it, maybe because of a failure in the pyIndego component?
![Error](https://user-images.githubusercontent.com/65425540/83198352-4c19eb00-a13f-11ea-8ebf-431188823676.jpg)

**Comment by UltraSub** [comment] 2020-05-28 22:09
Looks like a dupe of #46 
What model number does your Indego have?

**Comment by Ialocin7** [comment] 2020-05-28 22:26
My model number is 3600HB0103

**Comment by jm-73** [comment] 2020-06-03 04:51
Fixed in 0.8

**Closed by jm-73** 2020-06-03 04:51 UTC
