### ISSUE TITLE
Mower state detail not showing charging

### ISSUE THREAD

**Issue by Siggy101** [jm-73/Indego#72] opened 2020-06-11 13:40 UTC
In recent days, the mower state detail is no longer showing 'charging'.
It shows 'docked' instead.
It does show 'mowing', 'docked', 'sleeping', 'returning to dock - battery low' etc but no longer shows 'charging'.

![image](https://user-images.githubusercontent.com/41893936/84391886-dc553700-abf9-11ea-8861-b41f0350edf1.png)

**Comment by UltraSub** [comment] 2020-06-11 13:54
https://github.com/jm-73/Indego/releases/tag/1.0

> Corrected polling mechanism to poll only when mower is active and awake. This prevents vampire drain of the battery. Device is polled every hour when not active and mowing.

I suspect it has to do with this release. If it does, it's "collateral damage". You don't want the drain of the battery by constantly keeping it awake. It skews operation/running times and it is bad for battery life (much faster to the maximum number of charge cycles).

**Comment by jm-73** [comment] 2020-06-11 13:59
I am running the latest release on my test HA (1.2). It has shown Charging in detailed state today. I will double check next time my mower charges. @UltraSub Are you also experiencing this problem?

**Comment by Shamshala** [comment] 2020-06-11 13:59
Don't know now about v1.1 and v1.2 but i saw "Charging" state at v1.0 multiple times.

**Comment by UltraSub** [comment] 2020-06-11 14:01
Don't have it configured yet. Disabled because of the drain, already upgraded the component but didn't find the time yet to configure it and do Lovelace. Maybe tonight or tomorrow.

**Comment by Siggy101** [comment] 2020-06-11 14:22
I love the new releases not causing vampire drain so it would be a shame to have this collateral damage, if that's what it is.
For completeness, I had it on v0.9 then it was gone in v1.0 and v1.2.

**Comment by jm-73** [comment] 2020-06-11 14:37
You have tested 1.2? And it still doesnt show Charging? Could you run the Integration with the debug logging option when the mower is charging?

**Comment by jm-73** [comment] 2020-06-11 14:49
![image](https://user-images.githubusercontent.com/40487117/84401336-72da2600-ac03-11ea-877f-bb32d7ab8780.png)

**Comment by Siggy101** [comment] 2020-06-11 16:05
Yep. That image I shared was during charging on 1.2

Can you tell me how to enable debug and I'll do it.

**Comment by jm-73** [comment] 2020-06-11 16:48
This is from the README:

#configuration.yaml
logger:
  logs:
    custom_components.indego: debug

Put this in your configuration.yaml. Try to see what goes wrong. The log is a mess in the beginning. Sometimes it is easier to just let the log go for a while. Then make sure your mower is charging. Look in the log what the Indego calls are reporting. Or sen the whole log to me, through discord.

**Comment by Siggy101** [comment] 2020-06-11 17:36
Thanks for the pointers.
I will set it up to log, let it run and will send you the output tomorrow.

**Comment by Shamshala** [comment] 2020-06-12 10:18
Ok, Charging state on v1.2 confirmed, works for me as on v1.0

**Comment by jm-73** [comment] 2020-06-14 07:36
As I cannot reproduce the error, I need debug logs.

**Comment by Siggy101** [comment] 2020-06-15 07:57
I have pulled a few days of debug logs and will send them to you shortly.
Interestingly, I have seen it show a detailed state of 'charging' on some occasions and not on others.  Most peculiar.

**Comment by Siggy101** [comment] 2020-06-15 09:18
@jm-73 I sent you a friend request in discord.  If you accept then I can send you the logs.  Am ready when you are.
ps:  Mower is currently charging but displaying as 'docked' again so the problem persists.

**Comment by jm-73** [comment] 2020-06-15 09:20
Didnt get the request...

**Comment by Siggy101** [comment] 2020-06-15 09:38
Weird.  Are you jm-73#4466?

**Comment by jm-73** [comment] 2020-06-15 10:05
Discord: jmm_73

**Comment by jm-73** [comment] 2020-06-19 11:29
Fixed in 1.5

**Closed by jm-73** 2020-06-19 11:29 UTC
